#!/bin/bash

cbg="^bg(#d64937)"
cfg="^fg(#ffffff)"
ctbg="^bg(#d64937)"
ctfg="^fg(#2d2d2d)"
rt="^i($HOME/2bwm/right_triangle.xbm)"
lwst="^i($HOME/2bwm/left_workspace_triangle.xbm)"
tbg="^bg(#2d2d2d)"
tfg="^fg(#d64937)"


while true
do
	clock=`date +"%a %d %b %H:%M"`
  	echo "$ctbg$ctfg$lwst$cbg$cfg É $clock $tbg$tfg$rt"
	(cal)
	sleep 1
done
